name: release my app
on: 
  push:
    tags:
      - deploy*
jobs:
  RunUnitTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -la 
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Compile project
        run: mvn compile
      - name: Test project
        run: mvn test
      - run: echo "Application passed tests"
  ReleaseMyApp:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: ls -la 
      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          architecture: x64
      - name: Create JAR package
        run: mvn package
      - name: list compiled files
        run: ls -la target/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "target/my-ecommerce-0.1.jar"
          name: "Release JAR file"
          body: "Release new JAR file for the project"